name: aligner_gpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - audioread=2.1.8
  - decorator=4.4.1
  - ffmpeg=4.2
  - libflac=1.3.1
  - libiconv=1.15
  - libllvm8=8.0.1
  - libogg=1.3.2
  - librosa=0.7.2
  - libsndfile=1.0.28
  - libuuid=2.32.1
  - libvorbis=1.3.5
  - libxcb=1.13
  - numba=0.47.0
  - pyqt=5.6.0
  - pysoundfile=0.10.2
  - resampy=0.2.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - python=3.6.10
  - pytorch=1.5.0
  - cudatoolkit=9.2

